PM/urls.py
"""define PM's url model"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # main page
    url(r'^$', views.index, name='index'),
    # all project
    url(r'^projects/$', views.projects, name='projects'),
    # add new project 
    url(r'^new_project/$', views.new_project, name='new_project'),
    # delete project
    url(r'^del_project/(?P<project_id>\d+)/$', views.del_project, name='del_project'),
    # renew project
    url(r'^renew_project/(?P<project_id>\d+)/$', views.renew_project, name='renew_project'),
    # finished
    url(r'^finished/(?P<project_id>\d+)/$', views.finished, name='finished'),
    # search
    url(r'^search/$', views.search, name='search'),
]

PM_system/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('PM.urls', namespace='PM')),
    url(r'^users/', include('users.urls', namespace='users')),
]

users/urls.py
"""define users' url model"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # login and logout and register
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

PM/models.py
from django.db import models

class Project(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    deadline = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    finished_time = models.DateTimeField(auto_now_add=True)
    date_add = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

PM/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import Project

def index(request):
    """main page"""
    return render(request, 'PM/index.html')

def projects(request):
    """all projects page"""
    projects = Project.objects.order_by('date_add')
    context = {'projects':projects}
    return render(request,'PM/projects.html',context)

def new_project(request):
    """add new project"""
    if request.method == 'POST':
        """
        temp_name = request.POST['name']
        temp_author = request.POST.get(author)
        temp_year = request.POST.get('year')
        temp_month = request.POST['month']
        temp_day = request.POST['day']
        from django.utils import timezone
        """
        temp_project = Project(name=request.POST.get('name'), author=request.POST.get('author'), deadline=request.POST.get('deadline'), state='ing')
        temp_project.save()

        return HttpResponseRedirect(reverse('PM:projects'))

    return render(request, 'PM/new_project.html')

def del_project(request, project_id):
    project = Project.objects.get(id=project_id)
    context ={'project':project}
    if request.method == 'POST':
        Project.objects.filter(id=project_id).delete()
        return HttpResponseRedirect(reverse('PM:projects'))
    
    return render(request, 'PM/del_project.html', context)

def renew_project(request, project_id):
    """Let you renew the project"""
    project = Project.objects.get(id=project_id)
    
    if request.method == 'POST':
    # Second request
        from django.utils import timezone
        temp_project = Project(name=request.POST.get('name'), author=request.POST.get('author'), deadline=request.POST.get('deadline'), state='ing', finished_time=timezone.now())
        temp_project.save()

        Project.objects.filter(id=project_id).delete()
        return HttpResponseRedirect(reverse('PM:projects'))

    # First request, using instance project to pad the form
    context = {'project':project}
    return render(request, 'PM/renew_project.html', context)

def finished(request, project_id):
    project = Project.objects.get(id=project_id)
    from django.utils import timezone
    project.finished_time = timezone.now()
    project.state = 'finished'
    project.save()
    return HttpResponseRedirect(reverse('PM:projects'))
    #return render(request, 'PM/projects.html')

def search(request):
    search_content = request.GET.get('search_key')
    error_msg = ''

    if not search_content:
        error_msg = 'Please enter the key word'
        return render(request, 'PM/errors.html', {'error_msg':error_msg})

    projects = Project.objects.filter(name__icontains=search_content)
    return render(request, 'PM/search.html', {'error_msg': error_msg, 'projects': projects})

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """log out"""
    logout(request)
    return HttpResponseRedirect(reverse('PM:index'))

def register(request):
    """User register"""
    if request.method != 'POST':
        # empty register form 
        form = UserCreationForm()
    else:
        # handle fill in form 
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # auto log in and redirect
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('PM:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

PM/templates/PM/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>PM System</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  
  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
          
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'PM:index' %}">
              PM System</a>
        </div>
        
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'PM:projects' %}">Projects</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
        
      </div>
    </nav>
    
    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

PM/templates/PM/del_project.html
{% extends "PM/base.html" %}

{% block header %}
<h1>Deletion Confirm</h1>
{% endblock header %}

{% block content %}
<h3>
You will delete the project:</h3><div class="text" style="text-align:center;"><h1><font color="red">{{ project.name }}</font></h1></div>

<h3>Are you sure?</h3>


<form action="{% url 'PM:del_project' project.id %}" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="delete">
  <a href="{% url 'PM:projects' %}" method='get' class="btn btn-primary" role="button">cancel</a>
</form>
{% endblock content %}

PM/templates/PM/errors.html
{% extends "PM/base.html" %}
<h1>ERRORS</h1>
<p>Error:{{ error_msg }}
</p>

PM/templates/PM/index.html
{% extends "PM/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Project Management System</h1>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your own projects, and manage your projects you're doing.
  </h2>
  <h2>
    You will feel so lucky when you using this project management system.
  </h2>

{% endblock content %}

PM/templates/PM/new_project.html
{% extends "PM/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h1>Add new project</h1>
{% endblock header %}

{% block content %}

<form action="{% url 'PM:new_project' %}" method="post" name="new_project" class="form">
  {% csrf_token %}
  <p><span>Project Name:</span><input type="text" name="name"></p>
  <p><span>Author:</span><input type="text" name="author"></p>
  <p><span>Deadline:</span><input type="date" name="deadline"></p>
<div style="float:left;">
  <button name="submit" class="btn btn-primary">add</button>
  <a href="{% url 'PM:projects' %}" class="btn btn-primary" role="button">cancel</a>
</div>
</form>

{% endblock content %}

PM/templates/PM/projects.html
{% extends "PM/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h1>Projects</h1>
{% endblock header %}

{% block content %}

<form style="" class="form-inline mt-2 mt-md-0" action="{% url 'PM:search' %}" method='get'>
  {% csrf_token %}

<a class="btn btn-primary" href="{% url 'PM:new_project' %}" role="button">Add new project</a>
  <input name="search_key" class="form-control mr-sm-2" type="text" placeholder="Project Name" aria-label="Search" required>
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

</form>

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>name</th>
        <th>author</th>
        <th>deadline</th>
        <th>state</th>
        <th>date_added</th>
        <th>date_finished</th>
        <th>operation</th>
      </tr>
    </thead>
    <tbody>

{% for project in projects %}
  <tr>
    <td>{{ project.name }}</td>
    <td>{{ project.author }}</td>
    <td>{{ project.deadline }}</td>
    <td>{{ project.state }}</td>
    <td>{{ project.date_add|date:'M d, Y H:i' }}</td>
    <td>{{ project.finished_time|date:'M d, Y H:i' }}</td>
    
    <td><a href="{% url 'PM:finished' project.id %}" class="btn btn-info" role="button">finished</a><a href="{% url 'PM:renew_project' project.id %}" class="btn btn-warning" role="button">renew</a><a href="{% url 'PM:del_project' project.id %}" class="btn btn-danger" role="button">delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

PM/templates/PM/renew_project.html
{% extends "PM/base.html" %}

{% block header %}
<h1>Renew Project</h1>
{% endblock header %}

{% block content %}

<form action="{% url 'PM:renew_project' project.id %}" method="post" name="new_project">
  {% csrf_token %}
  <p><span>Project Name:</span><input type="text" name="name" value="{{ project.name }}"></p>
  <p><span>Author:</span><input type="text" name="author" value="{{ project.author }}"></p>
  <p><span>Deadline:</span><input type="date" name="deadline" value="{{ project.deadline }}"></p>

<div style="float:left;">
  <input class="btn btn-warning" type="submit" value="renew">
  <a href="{% url 'PM:projects' %}" method='get' class="btn btn-primary" role="button">cancel</a>
</div>
</form>

{% endblock content %}

PM/templates/PM/search.html
{% extends "PM/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h1>Search Result</h1>
{% endblock header %}

{% block content %}

<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>name</th>
        <th>author</th>
        <th>deadline</th>
        <th>state</th>
        <th>date_added</th>
        <th>date_finished</th>
        <th>operation</th>
      </tr>
    </thead>
    <tbody>

{% for project in projects %}
  <tr>
    <td>{{ project.name }}</td>
    <td>{{ project.author }}</td>
    <td>{{ project.deadline }}</td>
    <td>{{ project.state }}</td>
    <td>{{ project.date_add|date:'M d, Y H:i' }}</td>
    <td>{{ project.finished_time|date:'M d, Y H:i' }}</td>
    
    <td><a href="{% url 'PM:finished' project.id %}" class="btn btn-info" role="button">finished</a><a href="{% url 'PM:renew_project' project.id %}" class="btn btn-warning" role="button">renew</a><a href="{% url 'PM:del_project' project.id %}" class="btn btn-danger" role="button">delete</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends "PM/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
  {% endbuttons %}

  <input type="hidden" name="next" value="{% url 'PM:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "PM/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register an account</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'PM:index' %}" />
  </form>

{% endblock content %}